# Generated by Django 3.2.7 on 2021-10-27 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSie', '0002_grade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='name',
            new_name='id',
        ),
    ]
