# Generated by Django 3.2.7 on 2021-10-27 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appSie', '0004_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_group', to='appSie.grade'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('last_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('date_of_birth', models.DateTimeField(blank=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=100)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_student', to='appSie.grade')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_student', to='appSie.group')),
            ],
        ),
    ]
