# Generated by Django 3.2.7 on 2021-10-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSie', '0005_auto_20211027_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True),
        ),
    ]
