# Generated by Django 3.2.7 on 2021-10-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appSie', '0007_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
    ]
